[tool.poetry]
name = "py-ddd"
version = "0.1.0"
description = ""
authors = ["Ryan Mark <ma_xingmin@163.com>"]
readme = "README.md"
packages = [{include = "py_ddd"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
